/**
 * Per-instance Cloudflare DNS records for swctl named-tunnels (v0.7.4).
 *
 * Background: before v0.7.4, swctl named-tunnels relied on a wildcard
 * `*.<SW_PREVIEW_DOMAIN>` CNAME pointing at the cloudflared tunnel.
 * That wildcard catches EVERY subdomain — including ones the user wants
 * to use for Pages / Workers / R2 / etc. on the same root domain.
 * CF rejected new Worker Custom Domains because "the hostname is
 * already covered by *.y-tn.dev".
 *
 * Fix: drop the wildcard.  swctl creates a SPECIFIC CNAME per instance
 * on Start (`sw-<id>.<domain> -> <tunnel>.cfargotunnel.com`) and
 * deletes it on Stop.  Co-resident with Pages/Workers on the same zone
 * because each takes only the precise hostname it needs.
 *
 * Credentials are sourced from `~/.cloudflared/cert.pem` — the same
 * file cloudflared itself uses, so no separate token setup.  The
 * cert.pem holds an `ARGO TUNNEL TOKEN` block (PEM-looking but
 * actually a base64-encoded JSON object with `apiToken`, `zoneID`,
 * `accountID`).  This token is scoped to DNS:Edit + Tunnel:Edit on
 * the zone — exactly the scopes we need.
 *
 * Failure model: every step that returns non-200 surfaces as a
 * caller-facing `{ ok: false, error }` so the route handler can stop
 * the named-tunnel start before swctl actually spawns the connector.
 * Never throws.
 */

import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'

interface CfCreds { apiToken: string; zoneId: string; accountId: string }

let _credsCache: CfCreds | null = null

/**
 * Pull the apiToken + zoneID + accountID out of `~/.cloudflared/cert.pem`.
 * The file has a base64-encoded JSON blob between
 * `-----BEGIN ARGO TUNNEL TOKEN-----` and `-----END ARGO TUNNEL TOKEN-----`.
 *
 * Cached per-process — the cert.pem can be regenerated by
 * `cloudflared tunnel login` but that's rare; clearCfCredentialsCache()
 * lets tests reset between cases.
 */
export function readCfCredentials(): CfCreds | null {
  if (_credsCache) return _credsCache
  const certPath = path.join(os.homedir(), '.cloudflared', 'cert.pem')
  if (!fs.existsSync(certPath)) return null
  let raw: string
  try { raw = fs.readFileSync(certPath, 'utf-8') }
  catch { return null }
  const m = raw.match(
    /-----BEGIN ARGO TUNNEL TOKEN-----\s*([\s\S]+?)\s*-----END ARGO TUNNEL TOKEN-----/,
  )
  if (!m) return null
  const b64 = m[1].replace(/\s+/g, '')
  let json: any
  try { json = JSON.parse(Buffer.from(b64, 'base64').toString('utf-8')) }
  catch { return null }
  if (!json?.apiToken || !json?.zoneID || !json?.accountID) return null
  _credsCache = { apiToken: json.apiToken, zoneId: json.zoneID, accountId: json.accountID }
  return _credsCache
}

/** Reset the credentials cache.  Test-only. */
export function clearCfCredentialsCache(): void { _credsCache = null }

const CF_BASE = 'https://api.cloudflare.com/client/v4'

interface CfResult { status: number; body: any }
async function cfFetch(token: string, url: string, init: RequestInit = {}): Promise<CfResult> {
  const ctrl = new AbortController()
  // 10 s — CF API is normally <500 ms; a stalled socket shouldn't
  // hang a named-tunnel start for minutes.
  const timer = setTimeout(() => ctrl.abort(), 10_000)
  try {
    const r = await fetch(url, {
      ...init,
      headers: {
        Authorization: `Bearer ${token}`,
        'Content-Type': 'application/json',
        ...(init.headers || {}),
      },
      signal: ctrl.signal,
    })
    const body: any = await r.json().catch(() => ({}))
    return { status: r.status, body }
  } catch (e: any) {
    return { status: 0, body: { errors: [{ message: e?.message || String(e) }] } }
  } finally {
    clearTimeout(timer)
  }
}

function firstErr(r: CfResult): string {
  return r.body?.errors?.[0]?.message
      || r.body?.error
      || `HTTP ${r.status}`
}

export interface EnsureCnameResult {
  ok: boolean
  recordId?: string
  error?: string
}

/**
 * Idempotently ensure a proxied CNAME record exists at `hostname` with
 * content `target`.  Behaviour:
 *  - Existing CNAME with the right target → no-op, returns existing id.
 *  - Existing record with WRONG type or wrong target → PATCH it.
 *  - No existing record → POST a new one.
 *
 * Returns ok=false if credentials are missing OR any CF API call
 * fails.  Callers that need a tunnel to start should NOT proceed when
 * ok=false — that's the whole point of pre-arranging DNS.
 */
export async function ensureCname(hostname: string, target: string): Promise<EnsureCnameResult> {
  const creds = readCfCredentials()
  if (!creds) return { ok: false, error: 'No ~/.cloudflared/cert.pem with ARGO TUNNEL TOKEN — run `cloudflared tunnel login` first.' }
  const { apiToken, zoneId } = creds

  // Look up existing record by name.
  const list = await cfFetch(apiToken, `${CF_BASE}/zones/${zoneId}/dns_records?name=${encodeURIComponent(hostname)}`)
  if (list.status !== 200 || !list.body?.success) {
    return { ok: false, error: `DNS lookup failed: ${firstErr(list)}` }
  }
  const existing = (list.body.result || [])[0]

  // Already correct — no-op.
  if (existing
      && existing.type === 'CNAME'
      && existing.content === target
      && existing.proxied === true) {
    return { ok: true, recordId: existing.id }
  }

  if (existing) {
    // Patch in place — keeps the same id so the user's UI doesn't
    // jitter if they're watching the record list.
    const patch = await cfFetch(
      apiToken,
      `${CF_BASE}/zones/${zoneId}/dns_records/${existing.id}`,
      { method: 'PUT', body: JSON.stringify({ type: 'CNAME', name: hostname, content: target, proxied: true, ttl: 1 }) },
    )
    if (patch.status !== 200 || !patch.body?.success) {
      return { ok: false, error: `DNS update failed: ${firstErr(patch)}` }
    }
    return { ok: true, recordId: patch.body.result.id }
  }

  // Create new.
  const create = await cfFetch(
    apiToken,
    `${CF_BASE}/zones/${zoneId}/dns_records`,
    {
      method: 'POST',
      body: JSON.stringify({
        type: 'CNAME', name: hostname, content: target, proxied: true, ttl: 1,
        comment: 'swctl per-instance named-tunnel record (auto-managed; delete via UI Stop)',
      }),
    },
  )
  if (create.status !== 200 || !create.body?.success) {
    return { ok: false, error: `DNS create failed: ${firstErr(create)}` }
  }
  return { ok: true, recordId: create.body.result.id }
}

export interface DeleteCnameResult {
  ok: boolean
  /** True if a record was actually deleted; false if there was nothing to delete (also ok). */
  deleted: boolean
  error?: string
}

/**
 * Delete the CNAME record at `hostname` if it exists.  No-op if absent
 * (returns ok=true, deleted=false).  Safe to call from a Stop handler
 * regardless of whether Start ever ran — important because the
 * caller doesn't track DNS state separately.
 *
 * Why only "ours": we look up by exact hostname.  If the user
 * manually created a different record at the same name (e.g. they
 * pointed `sw-12345.y-tn.dev` at something else for testing), we'd
 * delete that too.  Acceptable trade-off: the namespace `sw-<id>`
 * is reserved for swctl by convention; if the user co-opts it,
 * they're already in unsupported territory.
 */
export async function deleteCname(hostname: string): Promise<DeleteCnameResult> {
  const creds = readCfCredentials()
  if (!creds) return { ok: false, deleted: false, error: 'No ~/.cloudflared/cert.pem' }
  const { apiToken, zoneId } = creds

  const list = await cfFetch(apiToken, `${CF_BASE}/zones/${zoneId}/dns_records?name=${encodeURIComponent(hostname)}`)
  if (list.status !== 200 || !list.body?.success) {
    return { ok: false, deleted: false, error: `DNS lookup failed: ${firstErr(list)}` }
  }
  const existing = (list.body.result || [])[0]
  if (!existing) return { ok: true, deleted: false }

  const del = await cfFetch(
    apiToken,
    `${CF_BASE}/zones/${zoneId}/dns_records/${existing.id}`,
    { method: 'DELETE' },
  )
  if (del.status !== 200 || !del.body?.success) {
    return { ok: false, deleted: false, error: `DNS delete failed: ${firstErr(del)}` }
  }
  return { ok: true, deleted: true }
}
